# Generated by Django 5.1.2 on 2024-10-18 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('is_depreciating', models.BooleanField(default=False)),
                ('depreciation_years', models.IntegerField(blank=True, null=True)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='finance.financialyear')),
            ],
        ),
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='finance.financialyear')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('depreciation_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_costs', to='finance.financialyear')),
            ],
        ),
    ]
