# Generated by Django 5.1.2 on 2024-10-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialyear',
            name='year',
            field=models.IntegerField(),
        ),
    ]
