# Generated by Django 5.1.2 on 2024-10-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_personaldetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='earning',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='earnings_attachments/'),
        ),
        migrations.AddField(
            model_name='earning',
            name='reference',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='earnings_attachments/'),
        ),
        migrations.AddField(
            model_name='expense',
            name='reference',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
